// <auto-generated />
using System;
using Flicked.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flicked.Api.Migrations
{
    [DbContext(typeof(FlickedDbContext))]
    [Migration("20260922102832_AddPlayerIsAdmin")]
    partial class AddPlayerIsAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flicked.Api.Models.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddresseeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequesterId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId", "AddresseeId")
                        .IsUnique();

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("Flicked.Api.Models.LoginCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("PlayerId");

                    b.ToTable("LoginCodes");
                });

            modelBuilder.Entity("Flicked.Api.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Map")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ScoreA")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreB")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 48213,
                            Map = "de_mirage",
                            PlayedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 18, 40, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ScoreA = 13,
                            ScoreB = 9
                        },
                        new
                        {
                            Id = 48190,
                            Map = "de_inferno",
                            PlayedAt = new DateTimeOffset(new DateTime(2026, 9, 21, 17, 5, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ScoreA = 10,
                            ScoreB = 13
                        },
                        new
                        {
                            Id = 48122,
                            Map = "de_nuke",
                            PlayedAt = new DateTimeOffset(new DateTime(2026, 9, 20, 21, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ScoreA = 13,
                            ScoreB = 4
                        },
                        new
                        {
                            Id = 48077,
                            Map = "de_ancient",
                            PlayedAt = new DateTimeOffset(new DateTime(2026, 9, 20, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ScoreA = 13,
                            ScoreB = 11
                        },
                        new
                        {
                            Id = 47951,
                            Map = "de_anubis",
                            PlayedAt = new DateTimeOffset(new DateTime(2026, 9, 19, 22, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ScoreA = 7,
                            ScoreB = 13
                        },
                        new
                        {
                            Id = 47903,
                            Map = "de_dust2",
                            PlayedAt = new DateTimeOffset(new DateTime(2026, 9, 18, 21, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ScoreA = 13,
                            ScoreB = 10
                        });
                });

            modelBuilder.Entity("Flicked.Api.Models.MatchPlayer", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Adr")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<int>("RatingDelta")
                        .HasColumnType("integer");

                    b.Property<int>("Team")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchPlayers");

                    b.HasData(
                        new
                        {
                            MatchId = 48213,
                            PlayerId = 1,
                            Adr = 97,
                            Deaths = 12,
                            Kills = 21,
                            RatingDelta = 24,
                            Team = 0
                        },
                        new
                        {
                            MatchId = 48190,
                            PlayerId = 1,
                            Adr = 72,
                            Deaths = 17,
                            Kills = 15,
                            RatingDelta = -19,
                            Team = 0
                        },
                        new
                        {
                            MatchId = 48122,
                            PlayerId = 1,
                            Adr = 91,
                            Deaths = 8,
                            Kills = 18,
                            RatingDelta = 21,
                            Team = 0
                        },
                        new
                        {
                            MatchId = 48077,
                            PlayerId = 1,
                            Adr = 80,
                            Deaths = 15,
                            Kills = 17,
                            RatingDelta = 18,
                            Team = 0
                        },
                        new
                        {
                            MatchId = 47951,
                            PlayerId = 1,
                            Adr = 61,
                            Deaths = 16,
                            Kills = 11,
                            RatingDelta = -22,
                            Team = 0
                        },
                        new
                        {
                            MatchId = 47903,
                            PlayerId = 1,
                            Adr = 88,
                            Deaths = 14,
                            Kills = 19,
                            RatingDelta = 20,
                            Team = 0
                        });
                });

            modelBuilder.Entity("Flicked.Api.Models.NewsPost", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Badge")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Body")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = "n6",
                            Badge = "0.2",
                            Body = new[] { "Parties are here. Invite friends from the list on the Play screen, or share your party code so they can join directly. The leader queues for everyone.", "Map veto is replaced by a map vote. After all ten players accept, everyone has 15 seconds to vote. The map with the most votes is played; a tie is settled at random.", "Also in this release: the launcher starts faster, fonts ship with the app, and the window no longer flashes white on open." },
                            Category = "patch",
                            Date = new DateOnly(2026, 9, 18),
                            Excerpt = "Queue with up to four friends, and pick the map together after everyone accepts.",
                            Title = "Alpha 0.2: parties and map vote"
                        },
                        new
                        {
                            Id = "n5",
                            Body = new[] { "You do not need a cluster to run FLICKED. The new guide in the repository shows how to run the backend, PostgreSQL, Redis and a CS2 dedicated server on a single machine.", "It covers ports, the match config, and how to point the launcher at your own server." },
                            Category = "update",
                            Date = new DateOnly(2026, 9, 15),
                            Excerpt = "A new guide walks through running the backend, database and one CS2 server on one box.",
                            Title = "Self-host FLICKED on a single machine"
                        },
                        new
                        {
                            Id = "n4",
                            Body = new[] { "Sign-ups for the first FLICKED Community Cup are open. Teams of five, single elimination, best of one until the final.", "Matches run on community-hosted servers. Brackets are published the day before the first round." },
                            Category = "event",
                            Date = new DateOnly(2026, 9, 12),
                            Excerpt = "Five-stack tournament, single elimination, played on community servers.",
                            Title = "Community Cup #1: sign-ups open"
                        },
                        new
                        {
                            Id = "n3",
                            Badge = "0.1.3",
                            Body = new[] { "Declining a match now always returns you to the Play screen. Before, a declined match could leave you searching with no way to cancel.", "Reconnecting to a live match is faster, and the server log keeps the full match history." },
                            Category = "patch",
                            Date = new DateOnly(2026, 9, 8),
                            Excerpt = "Fixes a case where a declined match kept you in queue, plus smaller stability fixes.",
                            Title = "Alpha 0.1.3: queue fixes"
                        },
                        new
                        {
                            Id = "n2",
                            Body = new[] { "Every match played on FLICKED now records a demo automatically. Demos are stored on the server that hosted the match.", "Server owners can set how long demos are kept." },
                            Category = "update",
                            Date = new DateOnly(2026, 9, 3),
                            Excerpt = "Demos are saved on the server and can be downloaded from the match page.",
                            Title = "Every match now records a demo"
                        },
                        new
                        {
                            Id = "n1",
                            Body = new[] { "Every Friday from 20:00 CET we play community 5v5s. More people in queue at the same time means shorter waits and closer matches." },
                            Category = "event",
                            Date = new DateOnly(2026, 8, 29),
                            Excerpt = "A standing night to find full stacks. Queue times drop, games get better.",
                            Title = "Weekly 5v5 night, Fridays at 20:00 CET"
                        });
                });

            modelBuilder.Entity("Flicked.Api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("SteamId")
                        .HasColumnType("text");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SteamId")
                        .IsUnique()
                        .HasFilter("\"SteamId\" IS NOT NULL");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = false,
                            Losses = 146,
                            Name = "kovac",
                            Rating = 2614,
                            Wins = 311
                        },
                        new
                        {
                            Id = 2,
                            IsAdmin = false,
                            Losses = 148,
                            Name = "Halden",
                            Rating = 2571,
                            Wins = 287
                        },
                        new
                        {
                            Id = 3,
                            IsAdmin = false,
                            Losses = 148,
                            Name = "Nyx",
                            Rating = 2498,
                            Wins = 264
                        },
                        new
                        {
                            Id = 4,
                            IsAdmin = false,
                            Losses = 147,
                            Name = "sprayz",
                            Rating = 2402,
                            Wins = 240
                        },
                        new
                        {
                            Id = 5,
                            IsAdmin = false,
                            Losses = 127,
                            Name = "quietus",
                            Rating = 2366,
                            Wins = 198
                        },
                        new
                        {
                            Id = 6,
                            IsAdmin = false,
                            Losses = 149,
                            Name = "reload",
                            Rating = 2291,
                            Wins = 215
                        },
                        new
                        {
                            Id = 7,
                            IsAdmin = false,
                            Losses = 122,
                            Name = "Brine",
                            Rating = 2240,
                            Wins = 176
                        },
                        new
                        {
                            Id = 8,
                            IsAdmin = false,
                            Losses = 122,
                            Name = "m0th",
                            Rating = 2187,
                            Wins = 169
                        },
                        new
                        {
                            Id = 9,
                            IsAdmin = false,
                            Losses = 119,
                            Name = "lowground",
                            Rating = 2105,
                            Wins = 151
                        },
                        new
                        {
                            Id = 10,
                            IsAdmin = false,
                            Losses = 117,
                            Name = "patchnote",
                            Rating = 2050,
                            Wins = 143
                        });
                });

            modelBuilder.Entity("Flicked.Api.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Flicked.Api.Models.Friendship", b =>
                {
                    b.HasOne("Flicked.Api.Models.Player", "Addressee")
                        .WithMany()
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flicked.Api.Models.Player", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Flicked.Api.Models.LoginCode", b =>
                {
                    b.HasOne("Flicked.Api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Flicked.Api.Models.MatchPlayer", b =>
                {
                    b.HasOne("Flicked.Api.Models.Match", "Match")
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flicked.Api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Flicked.Api.Models.Session", b =>
                {
                    b.HasOne("Flicked.Api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Flicked.Api.Models.Match", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
